#uselib "GocaineJIT.dll"
#func _GJIT_BEGIN "_GJIT_BEGIN" int,int,int
#func _GJIT_ADD "_GJIT_ADD" int,int,int,int,int,int,int
#func _GJIT_SUB "_GJIT_SUB" int,int,int,int,int,int,int
#func _GJIT_AND "_GJIT_AND" int,int,int,int,int,int,int
#func _GJIT_OR  "_GJIT_OR"  int,int,int,int,int,int,int
#func _GJIT_XOR "_GJIT_XOR" int,int,int,int,int,int,int
#func _GJIT_CMP "_GJIT_CMP" int,int,int,int,int,int,int
#func _GJIT_CALL "_GJIT_CALL" int,int,int,int
#func _GJIT_JMP  "_GJIT_JMP"  int,int,int,int
#func _GJIT_CCALL "_GJIT_CCALL" int,int,int,int,int
#func _GJIT_CJMP  "_GJIT_CJMP"  int,int,int,int,int
#func _GJIT_MOVRGINT "_GJIT_MOVRGINT" int,int,int,int,int,int
#func _GJIT_MOVRGRG  "_GJIT_MOVRGRG"  int,int,int,int,int,int
#func _GJIT_MOVRV    "_GJIT_MOVRV"    int,int,int,int,int
#func _GJIT_PUSH    "_GJIT_PUSH"    int,int,int,int,int
#func _GJIT_PUSHINT "_GJIT_PUSHINT" int,int,int,int,int
#func _GJIT_POP     "_GJIT_POP"     int,int,int,int,int
#func _GJIT_FINISHNR "_GJIT_FINISHNR" int,int,int
#func _GJIT_FINISH   "_GJIT_FINISH"   int,int,int
#func _GJIT_FINISHRR "_GJIT_FINISHRR" int,int,int,int,int
